# Generated by Django 5.1.5 on 2025-03-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('opportunity', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('Follow_up_1', 'Follow Up 1'), ('Follow_up_2', 'Follow Up 2'), ('Follow_up_3', 'Follow Up 3'), ('not_interested', 'Not Interested')], default='new', max_length=20)),
                ('activity', models.CharField(blank=True, choices=[('', 'No Activity'), ('call', 'Call'), ('email', 'Email'), ('whatsapp', 'Whatsapp')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('date', models.DateField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='firstapp.customer')),
            ],
        ),
    ]
