# Generated by Django 5.1.5 on 2025-03-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_calllog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallLog',
        ),
    ]
