# Generated by Django 5.1.5 on 2025-03-20 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_delete_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
